
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

import java_cup.runtime.*;
import java.util.*;
import java.util.Stack;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20141204 (SVN rev 60) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\114\000\002\002\004\000\002\002\004\000\002\016" +
    "\004\000\002\016\002\000\002\026\002\000\002\027\002" +
    "\000\002\030\002\000\002\017\021\000\002\031\002\000" +
    "\002\032\002\000\002\017\014\000\002\033\002\000\002" +
    "\024\005\000\002\024\002\000\002\015\004\000\002\015" +
    "\004\000\002\034\002\000\002\035\002\000\002\003\010" +
    "\000\002\004\004\000\002\004\002\000\002\005\003\000" +
    "\002\005\003\000\002\005\003\000\002\005\003\000\002" +
    "\005\003\000\002\005\003\000\002\005\003\000\002\005" +
    "\004\000\002\036\002\000\002\007\006\000\002\037\002" +
    "\000\002\010\006\000\002\040\002\000\002\041\002\000" +
    "\002\042\002\000\002\012\014\000\002\043\002\000\002" +
    "\013\016\000\002\044\002\000\002\045\002\000\002\014" +
    "\011\000\002\023\003\000\002\023\003\000\002\046\002" +
    "\000\002\011\010\000\002\047\002\000\002\011\006\000" +
    "\002\011\010\000\002\050\002\000\002\006\007\000\002" +
    "\006\006\000\002\025\006\000\002\025\005\000\002\025" +
    "\006\000\002\022\007\000\002\022\006\000\002\021\004" +
    "\000\002\021\003\000\002\020\005\000\002\020\005\000" +
    "\002\020\005\000\002\020\005\000\002\020\005\000\002" +
    "\020\005\000\002\020\005\000\002\020\005\000\002\020" +
    "\005\000\002\020\004\000\002\051\002\000\002\020\006" +
    "\000\002\020\003\000\002\020\003\000\002\020\003\000" +
    "\002\020\003\000\002\020\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\233\000\006\017\ufffe\047\ufffe\001\002\000\006\017" +
    "\011\047\012\001\002\000\004\002\006\001\002\000\004" +
    "\002\000\001\002\000\004\002\001\001\002\000\006\017" +
    "\uffff\047\uffff\001\002\000\004\020\ufff1\001\002\000\010" +
    "\024\014\025\016\053\013\001\002\000\004\010\ufff9\001" +
    "\002\000\004\053\uffd7\001\002\000\004\053\017\001\002" +
    "\000\004\053\uffd6\001\002\000\004\010\ufffd\001\002\000" +
    "\004\010\021\001\002\000\010\011\ufff4\024\ufff4\025\ufff4" +
    "\001\002\000\010\011\023\024\ufff6\025\ufff6\001\002\000" +
    "\004\050\105\001\002\000\006\024\014\025\016\001\002" +
    "\000\004\053\027\001\002\000\010\011\ufff5\024\ufff5\025" +
    "\ufff5\001\002\000\012\011\ufff3\012\072\024\ufff3\025\ufff3" +
    "\001\002\000\012\011\ufff2\024\ufff2\025\ufff2\053\031\001" +
    "\002\000\004\012\032\001\002\000\014\010\040\030\034" +
    "\053\033\054\035\055\037\001\002\000\052\004\uffba\005" +
    "\uffba\006\uffba\007\uffba\010\073\011\uffba\012\072\013\uffba" +
    "\014\uffba\015\uffba\016\uffba\026\uffba\027\uffba\030\uffba\032" +
    "\uffba\033\uffba\043\uffba\053\uffba\054\uffba\055\uffba\001\002" +
    "\000\014\010\040\030\034\053\033\054\035\055\037\001" +
    "\002\000\050\004\uffb8\005\uffb8\006\uffb8\007\uffb8\010\uffb8" +
    "\011\uffb8\013\uffb8\014\uffb8\015\uffb8\016\uffb8\026\uffb8\027" +
    "\uffb8\030\uffb8\032\uffb8\033\uffb8\043\uffb8\053\uffb8\054\uffb8" +
    "\055\uffb8\001\002\000\050\004\uffb9\005\uffb9\006\uffb9\007" +
    "\uffb9\010\uffb9\011\uffb9\013\uffb9\014\uffb9\015\uffb9\016\uffb9" +
    "\026\uffb9\027\uffb9\030\uffb9\032\uffb9\033\uffb9\043\uffb9\053" +
    "\031\054\uffb9\055\uffb9\001\002\000\050\004\uffb7\005\uffb7" +
    "\006\uffb7\007\uffb7\010\uffb7\011\uffb7\013\uffb7\014\uffb7\015" +
    "\uffb7\016\uffb7\026\uffb7\027\uffb7\030\uffb7\032\uffb7\033\uffb7" +
    "\043\uffb7\053\uffb7\054\uffb7\055\uffb7\001\002\000\014\010" +
    "\040\030\034\053\033\054\035\055\037\001\002\000\026" +
    "\004\046\005\043\006\050\007\044\013\053\014\052\015" +
    "\045\016\047\026\054\027\051\001\002\000\050\004\uffb6" +
    "\005\uffb6\006\uffb6\007\uffb6\010\uffb6\011\uffb6\013\uffb6\014" +
    "\uffb6\015\uffb6\016\uffb6\026\uffb6\027\uffb6\030\uffb6\032\uffb6" +
    "\033\uffb6\043\uffb6\053\uffb6\054\uffb6\055\uffb6\001\002\000" +
    "\014\010\040\030\034\053\033\054\035\055\037\001\002" +
    "\000\014\010\040\030\034\053\033\054\035\055\037\001" +
    "\002\000\014\010\040\030\034\053\033\054\035\055\037" +
    "\001\002\000\014\010\040\030\034\053\033\054\035\055" +
    "\037\001\002\000\014\010\040\030\034\053\033\054\035" +
    "\055\037\001\002\000\014\010\040\030\034\053\033\054" +
    "\035\055\037\001\002\000\014\010\040\030\034\053\033" +
    "\054\035\055\037\001\002\000\014\010\040\030\034\053" +
    "\033\054\035\055\037\001\002\000\056\004\uffca\005\uffca" +
    "\006\uffca\007\uffca\010\uffca\011\uffca\013\uffca\014\uffca\015" +
    "\uffca\016\uffca\024\uffca\025\uffca\026\uffca\027\uffca\030\uffca" +
    "\032\uffca\033\uffca\036\uffca\043\uffca\053\uffca\054\uffca\055" +
    "\uffca\001\002\000\014\010\040\030\034\053\033\054\035" +
    "\055\037\001\002\000\050\004\uffbf\005\uffbf\006\uffbf\007" +
    "\uffbf\010\uffbf\011\uffbf\013\uffbf\014\uffbf\015\uffbf\016\uffbf" +
    "\026\uffbf\027\uffbf\030\uffbf\032\uffbf\033\uffbf\043\uffbf\053" +
    "\uffbf\054\uffbf\055\uffbf\001\002\000\050\004\046\005\043" +
    "\006\050\007\044\010\uffc2\011\uffc2\013\uffc2\014\uffc2\015" +
    "\045\016\047\026\054\027\051\030\uffc2\032\uffc2\033\uffc2" +
    "\043\uffc2\053\uffc2\054\uffc2\055\uffc2\001\002\000\050\004" +
    "\uffbe\005\uffbe\006\uffbe\007\uffbe\010\uffbe\011\uffbe\013\uffbe" +
    "\014\uffbe\015\uffbe\016\uffbe\026\uffbe\027\uffbe\030\uffbe\032" +
    "\uffbe\033\uffbe\043\uffbe\053\uffbe\054\uffbe\055\uffbe\001\002" +
    "\000\050\004\uffc4\005\uffc4\006\uffc4\007\uffc4\010\uffc4\011" +
    "\uffc4\013\uffc4\014\uffc4\015\uffc4\016\uffc4\026\054\027\051" +
    "\030\uffc4\032\uffc4\033\uffc4\043\uffc4\053\uffc4\054\uffc4\055" +
    "\uffc4\001\002\000\050\004\046\005\043\006\050\007\044" +
    "\010\uffc0\011\uffc0\013\uffc0\014\uffc0\015\uffc0\016\uffc0\026" +
    "\054\027\051\030\uffc0\032\uffc0\033\uffc0\043\uffc0\053\uffc0" +
    "\054\uffc0\055\uffc0\001\002\000\050\004\uffc6\005\uffc6\006" +
    "\050\007\044\010\uffc6\011\uffc6\013\uffc6\014\uffc6\015\uffc6" +
    "\016\uffc6\026\054\027\051\030\uffc6\032\uffc6\033\uffc6\043" +
    "\uffc6\053\uffc6\054\uffc6\055\uffc6\001\002\000\050\004\046" +
    "\005\043\006\050\007\044\010\uffc1\011\uffc1\013\uffc1\014" +
    "\uffc1\015\uffc1\016\uffc1\026\054\027\051\030\uffc1\032\uffc1" +
    "\033\uffc1\043\uffc1\053\uffc1\054\uffc1\055\uffc1\001\002\000" +
    "\050\004\uffc3\005\uffc3\006\uffc3\007\uffc3\010\uffc3\011\uffc3" +
    "\013\uffc3\014\uffc3\015\uffc3\016\uffc3\026\054\027\051\030" +
    "\uffc3\032\uffc3\033\uffc3\043\uffc3\053\uffc3\054\uffc3\055\uffc3" +
    "\001\002\000\050\004\uffc5\005\uffc5\006\050\007\044\010" +
    "\uffc5\011\uffc5\013\uffc5\014\uffc5\015\uffc5\016\uffc5\026\054" +
    "\027\051\030\uffc5\032\uffc5\033\uffc5\043\uffc5\053\uffc5\054" +
    "\uffc5\055\uffc5\001\002\000\026\004\046\005\043\006\050" +
    "\007\044\011\uffbc\014\052\015\045\016\047\026\054\027" +
    "\051\001\002\000\004\011\070\001\002\000\050\004\uffbb" +
    "\005\uffbb\006\uffbb\007\uffbb\010\uffbb\011\uffbb\013\uffbb\014" +
    "\uffbb\015\uffbb\016\uffbb\026\uffbb\027\uffbb\030\uffbb\032\uffbb" +
    "\033\uffbb\043\uffbb\053\uffbb\054\uffbb\055\uffbb\001\002\000" +
    "\050\004\uffbd\005\uffbd\006\uffbd\007\uffbd\010\uffbd\011\uffbd" +
    "\013\uffbd\014\uffbd\015\uffbd\016\uffbd\026\uffbd\027\uffbd\030" +
    "\uffbd\032\uffbd\033\uffbd\043\uffbd\053\uffbd\054\uffbd\055\uffbd" +
    "\001\002\000\014\010\040\030\034\053\033\054\035\055" +
    "\037\001\002\000\016\010\040\011\076\030\034\053\033" +
    "\054\035\055\037\001\002\000\040\004\uffb9\005\uffb9\006" +
    "\uffb9\007\uffb9\010\uffb9\011\102\014\uffb9\015\uffb9\016\uffb9" +
    "\026\uffb9\027\uffb9\030\uffb9\053\031\054\uffb9\055\uffb9\001" +
    "\002\000\016\010\040\011\100\030\034\053\033\054\035" +
    "\055\037\001\002\000\050\004\uffcc\005\uffcc\006\uffcc\007" +
    "\uffcc\010\uffcc\011\uffcc\013\uffcc\014\uffcc\015\uffcc\016\uffcc" +
    "\026\uffcc\027\uffcc\030\uffcc\032\uffcc\033\uffcc\043\uffcc\053" +
    "\uffcc\054\uffcc\055\uffcc\001\002\000\040\004\046\005\043" +
    "\006\050\007\044\010\uffc7\011\uffc7\014\052\015\045\016" +
    "\047\026\054\027\051\030\uffc7\053\uffc7\054\uffc7\055\uffc7" +
    "\001\002\000\050\004\uffcd\005\uffcd\006\uffcd\007\uffcd\010" +
    "\uffcd\011\uffcd\013\uffcd\014\uffcd\015\uffcd\016\uffcd\026\uffcd" +
    "\027\uffcd\030\uffcd\032\uffcd\033\uffcd\043\uffcd\053\uffcd\054" +
    "\uffcd\055\uffcd\001\002\000\040\004\046\005\043\006\050" +
    "\007\044\010\uffc8\011\uffc8\014\052\015\045\016\047\026" +
    "\054\027\051\030\uffc8\053\uffc8\054\uffc8\055\uffc8\001\002" +
    "\000\050\004\uffcb\005\uffcb\006\uffcb\007\uffcb\010\uffcb\011" +
    "\uffcb\013\uffcb\014\uffcb\015\uffcb\016\uffcb\026\uffcb\027\uffcb" +
    "\030\uffcb\032\uffcb\033\uffcb\043\uffcb\053\uffcb\054\uffcb\055" +
    "\uffcb\001\002\000\026\004\046\005\043\006\050\007\044" +
    "\013\104\014\052\015\045\016\047\026\054\027\051\001" +
    "\002\000\056\004\uffc9\005\uffc9\006\uffc9\007\uffc9\010\uffc9" +
    "\011\uffc9\013\uffc9\014\uffc9\015\uffc9\016\uffc9\024\uffc9\025" +
    "\uffc9\026\uffc9\027\uffc9\030\uffc9\032\uffc9\033\uffc9\036\uffc9" +
    "\043\uffc9\053\uffc9\054\uffc9\055\uffc9\001\002\000\024\022" +
    "\ufffc\023\ufffc\024\ufffc\025\ufffc\031\ufffc\037\ufffc\045\ufffc" +
    "\052\ufffc\053\ufffc\001\002\000\024\022\uffed\023\uffed\024" +
    "\uffed\025\uffed\031\uffed\037\uffed\045\uffed\052\uffed\053\uffed" +
    "\001\002\000\024\022\110\023\122\024\014\025\016\031" +
    "\124\037\115\045\131\052\113\053\116\001\002\000\004" +
    "\053\216\001\002\000\004\053\203\001\002\000\040\021" +
    "\uffee\022\uffee\023\uffee\024\uffee\025\uffee\031\uffee\034\uffee" +
    "\035\uffee\037\uffee\044\uffee\045\uffee\046\uffee\051\uffee\052" +
    "\uffee\053\uffee\001\002\000\014\010\040\030\034\053\033" +
    "\054\035\055\037\001\002\000\006\036\174\053\031\001" +
    "\002\000\004\053\161\001\002\000\010\010\073\012\072" +
    "\036\155\001\002\000\040\021\uffec\022\uffec\023\uffec\024" +
    "\uffec\025\uffec\031\uffec\034\uffec\035\uffec\037\uffec\044\uffec" +
    "\045\uffec\046\uffec\051\uffec\052\uffec\053\uffec\001\002\000" +
    "\040\021\uffe6\022\uffe6\023\uffe6\024\uffe6\025\uffe6\031\uffe6" +
    "\034\uffe6\035\uffe6\037\uffe6\044\uffe6\045\uffe6\046\uffe6\051" +
    "\uffe6\052\uffe6\053\uffe6\001\002\000\040\021\uffe8\022\uffe8" +
    "\023\uffe8\024\uffe8\025\uffe8\031\uffe8\034\uffe8\035\uffe8\037" +
    "\uffe8\044\uffe8\045\uffe8\046\uffe8\051\uffe8\052\uffe8\053\uffe8" +
    "\001\002\000\014\010\040\030\034\053\033\054\035\055" +
    "\037\001\002\000\040\021\uffeb\022\uffeb\023\uffeb\024\uffeb" +
    "\025\uffeb\031\uffeb\034\uffeb\035\uffeb\037\uffeb\044\uffeb\045" +
    "\uffeb\046\uffeb\051\uffeb\052\uffeb\053\uffeb\001\002\000\014" +
    "\010\040\030\034\053\033\054\035\055\037\001\002\000" +
    "\004\032\140\001\002\000\040\021\uffe7\022\uffe7\023\uffe7" +
    "\024\uffe7\025\uffe7\031\uffe7\034\uffe7\035\uffe7\037\uffe7\044" +
    "\uffe7\045\uffe7\046\uffe7\051\uffe7\052\uffe7\053\uffe7\001\002" +
    "\000\040\021\uffe9\022\uffe9\023\uffe9\024\uffe9\025\uffe9\031" +
    "\uffe9\034\uffe9\035\uffe9\037\uffe9\044\uffe9\045\uffe9\046\uffe9" +
    "\051\uffe9\052\uffe9\053\uffe9\001\002\000\040\021\uffea\022" +
    "\uffea\023\uffea\024\uffea\025\uffea\031\uffea\034\uffea\035\uffea" +
    "\037\uffea\044\uffea\045\uffea\046\uffea\051\uffea\052\uffea\053" +
    "\uffea\001\002\000\014\010\040\030\034\053\033\054\035" +
    "\055\037\001\002\000\026\004\046\005\043\006\050\007" +
    "\044\014\052\015\045\016\047\026\054\027\051\043\uffda" +
    "\001\002\000\004\043\134\001\002\000\024\022\uffd9\023" +
    "\uffd9\024\uffd9\025\uffd9\031\uffd9\037\uffd9\045\uffd9\046\uffd9" +
    "\053\uffd9\001\002\000\024\022\uffed\023\uffed\024\uffed\025" +
    "\uffed\031\uffed\037\uffed\045\uffed\046\uffed\053\uffed\001\002" +
    "\000\024\022\110\023\122\024\014\025\016\031\124\037" +
    "\115\045\131\046\137\053\116\001\002\000\040\021\uffd8" +
    "\022\uffd8\023\uffd8\024\uffd8\025\uffd8\031\uffd8\034\uffd8\035" +
    "\uffd8\037\uffd8\044\uffd8\045\uffd8\046\uffd8\051\uffd8\052\uffd8" +
    "\053\uffd8\001\002\000\040\021\uffe5\022\uffe5\023\uffe5\024" +
    "\uffe5\025\uffe5\031\uffe5\034\uffe5\035\uffe5\037\uffe5\044\uffe5" +
    "\045\uffe5\046\uffe5\051\uffe5\052\uffe5\053\uffe5\001\002\000" +
    "\026\004\046\005\043\006\050\007\044\014\052\015\045" +
    "\016\047\026\054\027\051\033\uffe0\001\002\000\004\033" +
    "\143\001\002\000\024\022\uffdf\023\uffdf\024\uffdf\025\uffdf" +
    "\031\uffdf\034\uffdf\037\uffdf\045\uffdf\053\uffdf\001\002\000" +
    "\024\022\uffed\023\uffed\024\uffed\025\uffed\031\uffed\034\uffed" +
    "\037\uffed\045\uffed\053\uffed\001\002\000\024\022\110\023" +
    "\122\024\014\025\016\031\124\034\146\037\115\045\131" +
    "\053\116\001\002\000\024\022\uffde\023\uffde\024\uffde\025" +
    "\uffde\031\uffde\035\uffde\037\uffde\045\uffde\053\uffde\001\002" +
    "\000\024\022\uffed\023\uffed\024\uffed\025\uffed\031\uffed\035" +
    "\uffed\037\uffed\045\uffed\053\uffed\001\002\000\024\022\110" +
    "\023\122\024\014\025\016\031\124\035\151\037\115\045" +
    "\131\053\116\001\002\000\040\021\uffdd\022\uffdd\023\uffdd" +
    "\024\uffdd\025\uffdd\031\uffdd\034\uffdd\035\uffdd\037\uffdd\044" +
    "\uffdd\045\uffdd\046\uffdd\051\uffdd\052\uffdd\053\uffdd\001\002" +
    "\000\026\004\046\005\043\006\050\007\044\014\052\015" +
    "\045\016\047\026\054\027\051\032\uffe4\001\002\000\004" +
    "\032\154\001\002\000\040\021\uffe3\022\uffe3\023\uffe3\024" +
    "\uffe3\025\uffe3\031\uffe3\034\uffe3\035\uffe3\037\uffe3\044\uffe3" +
    "\045\uffe3\046\uffe3\051\uffe3\052\uffe3\053\uffe3\001\002\000" +
    "\014\010\040\030\034\053\033\054\035\055\037\001\002" +
    "\000\026\004\046\005\043\006\050\007\044\014\052\015" +
    "\045\016\047\026\054\027\051\032\uffd0\001\002\000\004" +
    "\032\160\001\002\000\040\021\uffcf\022\uffcf\023\uffcf\024" +
    "\uffcf\025\uffcf\031\uffcf\034\uffcf\035\uffcf\037\uffcf\044\uffcf" +
    "\045\uffcf\046\uffcf\051\uffcf\052\uffcf\053\uffcf\001\002\000" +
    "\004\040\162\001\002\000\004\054\163\001\002\000\004" +
    "\041\164\001\002\000\004\054\165\001\002\000\004\042" +
    "\166\001\002\000\004\054\167\001\002\000\004\043\170" +
    "\001\002\000\024\022\uffdc\023\uffdc\024\uffdc\025\uffdc\031" +
    "\uffdc\037\uffdc\044\uffdc\045\uffdc\053\uffdc\001\002\000\024" +
    "\022\uffed\023\uffed\024\uffed\025\uffed\031\uffed\037\uffed\044" +
    "\uffed\045\uffed\053\uffed\001\002\000\024\022\110\023\122" +
    "\024\014\025\016\031\124\037\115\044\173\045\131\053" +
    "\116\001\002\000\040\021\uffdb\022\uffdb\023\uffdb\024\uffdb" +
    "\025\uffdb\031\uffdb\034\uffdb\035\uffdb\037\uffdb\044\uffdb\045" +
    "\uffdb\046\uffdb\051\uffdb\052\uffdb\053\uffdb\001\002\000\014" +
    "\010\040\030\034\053\033\054\035\055\037\001\002\000" +
    "\026\004\046\005\043\006\050\007\044\014\052\015\045" +
    "\016\047\026\054\027\051\032\176\001\002\000\040\021" +
    "\uffce\022\uffce\023\uffce\024\uffce\025\uffce\031\uffce\034\uffce" +
    "\035\uffce\037\uffce\044\uffce\045\uffce\046\uffce\051\uffce\052" +
    "\uffce\053\uffce\001\002\000\026\004\046\005\043\006\050" +
    "\007\044\014\052\015\045\016\047\026\054\027\051\032" +
    "\200\001\002\000\004\051\ufffb\001\002\000\004\051\202" +
    "\001\002\000\006\017\ufffa\047\ufffa\001\002\000\010\012" +
    "\206\032\uffd3\036\205\001\002\000\004\032\215\001\002" +
    "\000\014\010\040\030\034\053\033\054\035\055\037\001" +
    "\002\000\004\054\207\001\002\000\004\013\210\001\002" +
    "\000\004\032\211\001\002\000\040\021\uffd1\022\uffd1\023" +
    "\uffd1\024\uffd1\025\uffd1\031\uffd1\034\uffd1\035\uffd1\037\uffd1" +
    "\044\uffd1\045\uffd1\046\uffd1\051\uffd1\052\uffd1\053\uffd1\001" +
    "\002\000\026\004\046\005\043\006\050\007\044\014\052" +
    "\015\045\016\047\026\054\027\051\032\uffd5\001\002\000" +
    "\004\032\214\001\002\000\040\021\uffd4\022\uffd4\023\uffd4" +
    "\024\uffd4\025\uffd4\031\uffd4\034\uffd4\035\uffd4\037\uffd4\044" +
    "\uffd4\045\uffd4\046\uffd4\051\uffd4\052\uffd4\053\uffd4\001\002" +
    "\000\040\021\uffd2\022\uffd2\023\uffd2\024\uffd2\025\uffd2\031" +
    "\uffd2\034\uffd2\035\uffd2\037\uffd2\044\uffd2\045\uffd2\046\uffd2" +
    "\051\uffd2\052\uffd2\053\uffd2\001\002\000\004\032\uffe2\001" +
    "\002\000\004\032\220\001\002\000\040\021\uffe1\022\uffe1" +
    "\023\uffe1\024\uffe1\025\uffe1\031\uffe1\034\uffe1\035\uffe1\037" +
    "\uffe1\044\uffe1\045\uffe1\046\uffe1\051\uffe1\052\uffe1\053\uffe1" +
    "\001\002\000\004\010\222\001\002\000\010\011\ufff4\024" +
    "\ufff4\025\ufff4\001\002\000\010\011\224\024\ufff6\025\ufff6" +
    "\001\002\000\004\050\225\001\002\000\024\022\ufff8\023" +
    "\ufff8\024\ufff8\025\ufff8\031\ufff8\037\ufff8\045\ufff8\051\ufff8" +
    "\053\ufff8\001\002\000\024\022\uffed\023\uffed\024\uffed\025" +
    "\uffed\031\uffed\037\uffed\045\uffed\051\uffed\053\uffed\001\002" +
    "\000\024\022\110\023\122\024\014\025\016\031\124\037" +
    "\115\045\131\051\230\053\116\001\002\000\006\017\ufff7" +
    "\047\ufff7\001\002\000\004\020\232\001\002\000\024\021" +
    "\ufff0\022\ufff0\023\ufff0\024\ufff0\025\ufff0\031\ufff0\037\ufff0" +
    "\045\ufff0\053\ufff0\001\002\000\024\021\uffed\022\uffed\023" +
    "\uffed\024\uffed\025\uffed\031\uffed\037\uffed\045\uffed\053\uffed" +
    "\001\002\000\024\021\235\022\110\023\122\024\014\025" +
    "\016\031\124\037\115\045\131\053\116\001\002\000\004" +
    "\002\uffef\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\233\000\006\002\004\016\003\001\001\000\006\003" +
    "\006\017\007\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\034\230\001" +
    "\001\000\004\023\014\001\001\000\004\031\220\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\026\017\001\001\000\002\001\001\000\004\024\021" +
    "\001\001\000\004\033\023\001\001\000\002\001\001\000" +
    "\006\015\025\023\024\001\001\000\004\022\027\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\010\020\040\022\035\025\041\001\001" +
    "\000\002\001\001\000\010\020\070\022\035\025\041\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\010\020\065\022\035\025\041\001\001\000\002\001" +
    "\001\000\002\001\001\000\010\020\064\022\035\025\041" +
    "\001\001\000\010\020\063\022\035\025\041\001\001\000" +
    "\010\020\062\022\035\025\041\001\001\000\010\020\061" +
    "\022\035\025\041\001\001\000\010\020\060\022\035\025" +
    "\041\001\001\000\010\020\057\022\035\025\041\001\001" +
    "\000\010\020\056\022\035\025\041\001\001\000\010\020" +
    "\055\022\035\025\041\001\001\000\002\001\001\000\010" +
    "\020\054\022\035\025\041\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\051\066\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\010\020" +
    "\102\022\035\025\041\001\001\000\012\020\076\021\074" +
    "\022\073\025\041\001\001\000\002\001\001\000\010\020" +
    "\100\022\035\025\041\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\027\105" +
    "\001\001\000\004\004\106\001\001\000\030\005\111\006" +
    "\122\007\127\010\126\011\116\012\120\013\125\014\117" +
    "\022\113\023\110\025\124\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\010\020\176\022\035" +
    "\025\041\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\010\020\151\022\035\025\041\001\001\000" +
    "\002\001\001\000\010\020\140\022\035\025\041\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\010\020\131\022\035\025\041\001\001" +
    "\000\004\044\132\001\001\000\002\001\001\000\004\045" +
    "\134\001\001\000\004\004\135\001\001\000\030\005\111" +
    "\006\122\007\127\010\126\011\116\012\120\013\125\014" +
    "\117\022\113\023\110\025\124\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\040\141\001\001\000\002\001" +
    "\001\000\004\041\143\001\001\000\004\004\144\001\001" +
    "\000\030\005\111\006\122\007\127\010\126\011\116\012" +
    "\120\013\125\014\117\022\113\023\110\025\124\001\001" +
    "\000\004\042\146\001\001\000\004\004\147\001\001\000" +
    "\030\005\111\006\122\007\127\010\126\011\116\012\120" +
    "\013\125\014\117\022\113\023\110\025\124\001\001\000" +
    "\002\001\001\000\004\036\152\001\001\000\002\001\001" +
    "\000\002\001\001\000\010\020\155\022\035\025\041\001" +
    "\001\000\004\050\156\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\043\170\001\001\000\004\004" +
    "\171\001\001\000\030\005\111\006\122\007\127\010\126" +
    "\011\116\012\120\013\125\014\117\022\113\023\110\025" +
    "\124\001\001\000\002\001\001\000\010\020\174\022\035" +
    "\025\041\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\030\200\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\047\203\001\001\000\002\001" +
    "\001\000\010\020\211\022\035\025\041\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\046\212\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\037\216\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\024\222\001\001\000\004\033\023\001\001\000\002\001" +
    "\001\000\004\032\225\001\001\000\004\004\226\001\001" +
    "\000\030\005\111\006\122\007\127\010\126\011\116\012" +
    "\120\013\125\014\117\022\113\023\110\025\124\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\035\232\001" +
    "\001\000\004\004\233\001\001\000\030\005\111\006\122" +
    "\007\127\010\126\011\116\012\120\013\125\014\117\022" +
    "\113\023\110\025\124\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}




  //classe para permitir salvar tipo do token e o valor.
   class table_symbol {

      private String tipo;
      private String valor;
      private int Escopo;
      private boolean funcao = false;
      private boolean vetor = false;

      table_symbol(String tipo, String valor){
         this.tipo = tipo;
         this.valor = valor;
      }

      table_symbol(String tipo){
         this.tipo = tipo;
      }
      
      table_symbol(String tipo, int Escopo){
         this.tipo = tipo;
         this.Escopo = Escopo;
      }

      table_symbol(String tipo, int Escopo, boolean vetor){
         this.tipo = tipo;
         this.Escopo = Escopo;
         this.vetor = vetor;
      }
      
      table_symbol(String tipo, boolean funcao){
         this.funcao = funcao;
         this.vetor = vetor;
         this.tipo = tipo;
         this.Escopo = Escopo;
      }


      public String getTipo(){
         return tipo;
      }

      public String getValor(){
         return valor;
      }

      public void setValor(String valor){
         this.valor = valor;
      }

      public int getEscopo(){
         return Escopo;
      }

      public boolean getFunc(){
         return funcao;
      }
   }   

/** table of declared symbols -- contains production parts indexed by name */
   private Hashtable<String, table_symbol> symT = new Hashtable<String, table_symbol>();
   private static final String LEFT_PAR = "(";
   private static final String RIGHT_PAR = ")";
   private int POS = 0;
   private int Escopo = 1;
   private boolean controla_virg = false;
    /* Change the method report_error so it will display the line and
       column of where the error occurred in the input as well as the
       reason for the error which is passed into the method in the
       String 'message'. */
   public void report_error(String message, Object info) {
   
        /* Create a StringBuilder called 'm' with the string 'Error' in it. */
      StringBuilder m = new StringBuilder("Error");

      /* Check if the information passed to the method is the same
         type as the type java_cup.runtime.Symbol. */
      if (info instanceof java_cup.runtime.Symbol) {
         /* Declare a java_cup.runtime.Symbol object 's' with the
            information in the object info that is being typecasted
            as a java_cup.runtime.Symbol object. */
         java_cup.runtime.Symbol s = ((java_cup.runtime.Symbol) info);

         /* Check if the line number in the input is greater or
            equal to zero. */
         if (s.left >= 0) {                
               /* Add to the end of the StringBuilder error message
                  the line number of the error in the input. */
               m.append(" in line "+(s.left+1));   
               /* Check if the column number in the input is greater
                  or equal to zero. */
               if (s.right >= 0)                    
                  /* Add to the end of the StringBuilder error message
                     the column number of the error in the input. */
                  m.append(", column "+(s.right+1));
         }
      }
   
        /* Add to the end of the StringBuilder error message created in
         this method the message that was passed into this method. */
      m.append(" : "+message);

      /* Print the contents of the StringBuilder 'm', which contains
         an error message, out on a line. */
      System.err.println(m);
   }

    /* Change the method report_fatal_error so when it reports a fatal
       error it will display the line and column number of where the
       fatal error occurred in the input as well as the reason for the
       fatal error which is passed into the method in the object
       'message' and then exit.*/
   public void report_fatal_error(String message, Object info) {
      report_error(message, info);
      System.exit(1);
   }

   public void format_code(){
      for(int i=0; i < POS * 3; i++){
         System.out.print(" ");
      }
   }

    
   public void update_symT(String id, String valor){

      table_symbol t = symT.get(id);
      t.setValor(valor);
      symT.replace(id,t);

   }

   public String check_expr(String e1, String e2){

      String res;
      
      if(! symT.containsKey(e1)) {
         report_fatal_error(e1 + "Nao declarada !!", null);
      }   
      
      if( symT.get(e1).getFunc() )
         report_fatal_error("Erro na variavel" + e1, null);

      if(e2 == null){
         table_symbol te1 = symT.get(e1);
         String tp1 = te1.getTipo();
         res = tp1;
      } else {


         if(! symT.containsKey(e2)) 
            report_fatal_error(e2 + "Nao declarada !", null);
         

         if( symT.get(e2).getFunc() )
            report_fatal_error(e2 + " É uma função ! ", null);
            
         table_symbol te1 = symT.get(e1);
         table_symbol te2 = symT.get(e2);

         String tp1 = te1.getTipo();
         String tp2 = te2.getTipo();

         if(tp1.equals(tp2)){
            res = tp1;
         } else {
            res =  "FLOAT";
         }
      }
   return res;
}



    /**************** emit code *****************/

    public void emit_program(){

       System.out.print("#include<stdio.h>\n");
       System.out.print("#include<stdlib.h>\n");
       System.out.print("\nint main()");

    }

    public void emit_startprogram(){

       System.out.print("{\n");

    }

   public void emit_return(){

      System.out.print("return 0;\n");

   }

   public void emit_semi(){
      System.out.print(";\n");
   }

   public void emit_thenn(){
        System.out.print("{\n");
    }

    public void emit_elsee(){
        System.out.print("else{\n");
    }

    public void emit_endelsee(){
        System.out.print("}\n");
    }

   public void emit_declare_variable_with_value(String id, String value, String tipo){

      if(symT.containsKey(id)){
         report_fatal_error("Variável duplicada: " + id,null);
      }
      symT.put(id,new table_symbol(tipo,Escopo));
      System.out.print(id + "=" + value); 
            
   }

   public void emit_declare_variable_without_value(String id, String tipo){
      
      if(symT.containsKey(id)){
         report_fatal_error("Variável duplicada: " + id,null);
      } 

      symT.put(id,new table_symbol(tipo,Escopo));
      System.out.print(id); 
   }

   public void emit_assign_id_expr(String id, String value){
      
      if(! symT.containsKey(id)) {
         report_fatal_error("Variavel nao declarada: " + id, null);
      } else {    
         if( symT.get(id).getFunc() )
            report_fatal_error("Variavel é uma função: " + id, null);

         System.out.print(id + "=" + value); 
         update_symT(id,value);
      }

   }
    
   public void emit_if(String e){

      System.out.print("if(" + e + ")");
   }


   public void emit_escreva(String id){
   
      if(! symT.containsKey(id)) {
         report_fatal_error("Variavel nao declarada: " + id, null);
      } else {    

         String tipo = symT.get(id).getTipo();

         if(tipo.equals("INT")) {
            System.out.print("printf(\"%d\\n\"," + id + ")") ;
         } else {
            System.out.print("printf(\"%f\\n\"," + id + ")");
         }   
      }
   }


   public void emit_leia(String id){

      if(! symT.containsKey(id)) {
         report_fatal_error("Variavel nao declarada: " + id, null);
      } else {    
         String tipo = (symT.get(id)).getTipo();

         if(tipo.equals("INT")) {
            System.out.print("scanf(\"%d\",&" + id + ")");
         } else {
            System.out.print("scanf(\"%f\",&" + id + ")");
         }   
      }
   }


   public void emit_vector(String id, String num){

      System.out.print(id + "[" + num + "];\n");

   }


   public void emit_func(String id, String e){
      System.out.print(id + "(" + e +");\n");
   }


   public void emit_inteiro(){
      System.out.print("int ");
   }


   public void emit_flutuante(){
      System.out.print("float ");
   }


   public void emit_declare_vector(String t, String id, String i){

      if(symT.containsKey(id)){
         report_fatal_error("Variável duplicada: " + id, null);
      } 

      symT.put(id,new table_symbol(t,Escopo, true));
      System.out.print(id + "["+i+"]");

   }


   public void emit_assign_vector(String v, String e){
      
      String id = v.substring(0,v.indexOf("["));

      if(! symT.containsKey(id)) {
         report_fatal_error("Vetor não declarado: " + id + "[]", null);
      }

      System.out.print(v+"="+e+";\n");
   }


   public String Checa_vetor(String v){

      String id = v.substring(0,v.indexOf("["));
      
      if(symT.containsKey(id)){
         symT.put(v,new table_symbol(symT.get(id).getTipo()));
         return v;
      
      } else {
         report_fatal_error("Vetor não declarado " + id + "[]", null);
      }

      return null; 

   }


   public void declare_param(String t, String id){

      if(symT.containsKey(id)) {
         report_fatal_error("Variável duplicada: " + id, null);
      } 

      symT.put(id,new table_symbol(t,Escopo));
   }


   public void emit_declare_func(String t, String id){
      
      if(symT.containsKey(id)) {
         report_fatal_error("Função duplicada: " + id + "()", null);
      } 

      symT.put(id,new table_symbol(t,true));

   }


   public String Checa_chamafunc(String f){

      String id = f.substring(0,f.indexOf("("));
      if( !symT.containsKey( id ) ) {
         report_fatal_error("Função não declarada: " + id + "()", null);
      }

      if(! symT.get(id).getFunc() )
         report_fatal_error("Função não declarada: " + id + "()", null);

      symT.put( f, new table_symbol( symT.get(id).getTipo() ) );

      return f;
   }

   public void limpar_escop(){

      ArrayList<String> lista = new ArrayList<String>();
      symT.forEach( (k,v) -> { 
         if(v.getEscopo() == Escopo){
            lista.add(k);
         }   
      });

      lista.forEach( (k) -> {
         symT.remove(k);
      });

   }



/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$parser$actions {
  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$parser$do_action_part00000000(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // s ::= listafuncao program 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("s",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= s EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // listafuncao ::= listafuncao func 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("listafuncao",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // listafuncao ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("listafuncao",12, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // NT$0 ::= 
            {
              Object RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
 System.out.print( id + "( ");
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$0",20, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // NT$1 ::= 
            {
              Object RESULT =(Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-6)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
 System.out.println("){"); emit_declare_func(t,id); POS++; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$1",21, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // NT$2 ::= 
            {
              Object RESULT =(Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-11)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-11)).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-11)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-10)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-10)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-10)).value;
		int valueleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int valueright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String value = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
 format_code(); System.out.println("return " + value + ";\n}\n"); POS--; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$2",22, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // func ::= FUNCAO tipo ID NT$0 LPAREN list_param RPAREN STARTFUNC NT$1 list_command RETORNO expr SEMI NT$2 ENDFUNC 
            {
              Object RESULT =null;
              // propagate RESULT from NT$2
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-13)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-13)).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-13)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-12)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-12)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-12)).value;
		int valueleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int valueright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String value = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		 limpar_escop();
              CUP$parser$result = parser.getSymbolFactory().newSymbol("func",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-14)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // NT$3 ::= 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
 System.out.print( "void " + id + "( "); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$3",23, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // NT$4 ::= 
            {
              Object RESULT =(Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
 System.out.println("){"); emit_declare_func("void",id); POS++; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$4",24, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // func ::= FUNCAO ID NT$3 LPAREN list_param RPAREN STARTFUNC NT$4 list_command ENDFUNC 
            {
              Object RESULT =null;
              // propagate RESULT from NT$4
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-9)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-9)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-9)).value;
		 format_code(); System.out.println("\n}\n"); POS--;  limpar_escop(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("func",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-9)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // NT$5 ::= 
            {
              String RESULT =null;
   if(controla_virg == true){ System.out.print(",");}     
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$5",25, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // list_param ::= list_param NT$5 param 
            {
              String RESULT =null;
              // propagate RESULT from NT$5
                RESULT = (String) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		    controla_virg = true;      
              CUP$parser$result = parser.getSymbolFactory().newSymbol("list_param",18, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // list_param ::= 
            {
              String RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("list_param",18, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // param ::= tipo ID 
            {
              Object RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 declare_param(t,id); System.out.print(id+" "); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("param",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // param ::= tipo vetor 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("param",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // NT$6 ::= 
            {
              Object RESULT =null;
 emit_program();               
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$6",26, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // NT$7 ::= 
            {
              Object RESULT =(Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
 emit_startprogram() ; POS++;       
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$7",27, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // program ::= PROGRAM NT$6 STARTPRG NT$7 list_command ENDPRG 
            {
              Object RESULT =null;
              // propagate RESULT from NT$7
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		 emit_return(); POS--; format_code(); System.out.println("}") ;        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("program",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // list_command ::= list_command command 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("list_command",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // list_command ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("list_command",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // command ::= declare_variable 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("command",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // command ::= assign 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("command",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // command ::= writel 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("command",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // command ::= readl 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("command",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // command ::= iff 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("command",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // command ::= for 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("command",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // command ::= while 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("command",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // command ::= chamafunc SEMI 
            {
              Object RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int fright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String f = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 format_code(); System.out.println(f+";");
              CUP$parser$result = parser.getSymbolFactory().newSymbol("command",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // NT$8 ::= 
            {
              Object RESULT =null;
		int valueleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int valueright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String value = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
 format_code(); emit_escreva(value);  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$8",28, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // writel ::= WRITELINE expr NT$8 SEMI 
            {
              Object RESULT =null;
              // propagate RESULT from NT$8
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int valueleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int valueright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String value = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		 emit_semi();          
              CUP$parser$result = parser.getSymbolFactory().newSymbol("writel",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // NT$9 ::= 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
 format_code(); emit_leia(id);   
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$9",29, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // readl ::= READLINE ID NT$9 SEMI 
            {
              Object RESULT =null;
              // propagate RESULT from NT$9
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		 emit_semi();     
              CUP$parser$result = parser.getSymbolFactory().newSymbol("readl",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // NT$10 ::= 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
 format_code(); emit_if(e);  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$10",30, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // NT$11 ::= 
            {
              Object RESULT =(Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
 System.out.println("{"); POS++; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$11",31, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // NT$12 ::= 
            {
              Object RESULT =(Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
 POS--; format_code(); System.out.print("}\n"); format_code(); emit_elsee(); POS++; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$12",32, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // iff ::= IFF expr NT$10 THENN NT$11 list_command ELSEE NT$12 list_command ENDELSE 
            {
              Object RESULT =null;
              // propagate RESULT from NT$12
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-8)).value;
		 POS--; format_code(); System.out.print("}\n"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("iff",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-9)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // NT$13 ::= 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-7)).value;
		int it1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int it1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		String it1 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int it2left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int it2right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String it2 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int it3left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int it3right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String it3 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
      System.out.print("for(" + id + "=" + it1 + ";" + id + "<" + it2 + ";" + id + "+=" + it3 + "){\n"); format_code();  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$13",33, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // for ::= PARA ID DE INTT ATE INTT PASSO INTT FACA NT$13 list_command FIMPARA 
            {
              Object RESULT =null;
              // propagate RESULT from NT$13
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-10)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-10)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-10)).value;
		int it1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)).left;
		int it1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)).right;
		String it1 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-8)).value;
		int it2left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).left;
		int it2right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).right;
		String it2 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-6)).value;
		int it3left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int it3right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		String it3 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		 System.out.print("}\n"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("for",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-11)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // NT$14 ::= 
            {
              Object RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
   System.out.print("while(" + i);   
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$14",34, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // NT$15 ::= 
            {
              Object RESULT =(Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int ileft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
   System.out.print("){\n");   
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$15",35, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // while ::= ENQUANTO expr NT$14 FACA NT$15 list_command FIMENQUANTO 
            {
              Object RESULT =null;
              // propagate RESULT from NT$15
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int ileft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		   System.out.print("}\n");   
              CUP$parser$result = parser.getSymbolFactory().newSymbol("while",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // tipo ::= DECLINT 
            {
              String RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object t = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = "INT"  ; format_code();  emit_inteiro();   
              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo",17, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // tipo ::= DECLFLOAT 
            {
              String RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object t = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = "FLOAT"; format_code();  emit_flutuante(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo",17, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // NT$16 ::= 
            {
              Object RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int valueleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int valueright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String value = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
 emit_declare_variable_with_value(id,value,t);  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$16",36, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // declare_variable ::= tipo ID ATTRIB expr NT$16 SEMI 
            {
              Object RESULT =null;
              // propagate RESULT from NT$16
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int valueleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int valueright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String value = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		 emit_semi(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("declare_variable",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // NT$17 ::= 
            {
              Object RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
 emit_declare_variable_without_value(id,t); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$17",37, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // declare_variable ::= tipo ID NT$17 SEMI 
            {
              Object RESULT =null;
              // propagate RESULT from NT$17
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		 emit_semi();  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("declare_variable",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // declare_variable ::= tipo ID LBRCKT INTT RBRCKT SEMI 
            {
              Object RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int ileft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		 emit_declare_vector(t,id,i); emit_semi(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("declare_variable",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // NT$18 ::= 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int valueleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int valueright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String value = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
 format_code(); emit_assign_id_expr(id,value); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$18",38, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // assign ::= ID ATTRIB expr NT$18 SEMI 
            {
              Object RESULT =null;
              // propagate RESULT from NT$18
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int valueleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int valueright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String value = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		 emit_semi(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("assign",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // assign ::= vetor ATTRIB expr SEMI 
            {
              Object RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String v = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 format_code(); emit_assign_vector(v,e);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("assign",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // chamafunc ::= ID LPAREN list_param_func RPAREN 
            {
              String RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = id + "("+ e +")"; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("chamafunc",19, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // chamafunc ::= ID LPAREN RPAREN 
            {
              String RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		 RESULT = id + "()"; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("chamafunc",19, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // chamafunc ::= ID LPAREN vetor RPAREN 
            {
              String RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int vleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String v = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = id+"(" + v + ")"; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("chamafunc",19, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // vetor ::= vetor ID LBRCKT expr RBRCKT 
            {
              String RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		String v = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int ileft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 if(v!=null) RESULT = v + ", " + id+"["+i+"]"; else RESULT = id+"["+i+"]"; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("vetor",16, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // vetor ::= ID LBRCKT expr RBRCKT 
            {
              String RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int ileft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = id+"["+i+"]"; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("vetor",16, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // list_param_func ::= list_param_func expr 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = e1 +","+ e; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("list_param_func",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // list_param_func ::= expr 
            {
              String RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = e;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("list_param_func",15, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // expr ::= expr PLUS expr 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT =  e1 + "+" + e2;  symT.put(RESULT,new table_symbol(check_expr(e1,e2),RESULT));  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // expr ::= expr MINUS expr 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT =  e1 + "-" + e2;  symT.put(RESULT,new table_symbol(check_expr(e1,e2),RESULT));  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // expr ::= expr TIMES expr 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT =  e1 + "*" + e2;  symT.put(RESULT,new table_symbol(check_expr(e1,e2),RESULT));  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // expr ::= expr DIVIDE expr 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT =  e1 + "/" + e2;  symT.put(RESULT,new table_symbol(check_expr(e1,e2),RESULT));  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // expr ::= expr EQUALS expr 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT =  e1 + "==" + e2; symT.put(RESULT,new table_symbol(check_expr(e1,e2),RESULT));  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // expr ::= expr GREATER expr 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT =  e1 + ">" + e2;  symT.put(RESULT,new table_symbol(check_expr(e1,e2),RESULT));  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // expr ::= expr LESS expr 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT =  e1 + "<" + e2;  symT.put(RESULT,new table_symbol(check_expr(e1,e2),RESULT));  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // expr ::= expr E expr 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT =  e1 + "&&" + e2; symT.put(RESULT,new table_symbol(check_expr(e1,e2),RESULT));  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // expr ::= expr OU expr 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT =  e1 + "||" + e2; symT.put(RESULT,new table_symbol(check_expr(e1,e2),RESULT));  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // expr ::= NAO expr 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT =   "!" + e1;  symT.put(RESULT,new table_symbol(check_expr(e1,null),RESULT));  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // NT$19 ::= 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
 RESULT =  "(" + e1  + ")";symT.put(RESULT,new table_symbol(check_expr(e1,null),RESULT)); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$19",39, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // expr ::= LPAREN expr NT$19 RPAREN 
            {
              String RESULT =null;
              // propagate RESULT from NT$19
                RESULT = (String) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // expr ::= ID 
            {
              String RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = i;                                                          
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // expr ::= vetor 
            {
              String RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String v = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = Checa_vetor(v);                                         
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 73: // expr ::= INTT 
            {
              String RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = n;  symT.put(n,new table_symbol("INT",n));                  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 74: // expr ::= FLOATT 
            {
              String RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = n;  symT.put(n,new table_symbol("FLOAT",n));                
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 75: // expr ::= chamafunc 
            {
              String RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String f = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = Checa_chamafunc(f); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
              return CUP$parser$do_action_part00000000(
                               CUP$parser$act_num,
                               CUP$parser$parser,
                               CUP$parser$stack,
                               CUP$parser$top);
    }
}

}
